# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pr:
  branches:
    include:
      - master
      - rel/*
  drafts: false

trigger:
  - main

pool:
  vmImage: ubuntu-latest

variables:
  isDevBranch: $[eq(variables['Build.SourceBranch'], 'refs/heads/develop')]
  isReleaseBranch: $[startsWith(variables['Build.SourceBranch'], 'refs/heads/release')]
  isMainBranch: $[eq(variables['Build.SourceBranch'], 'refs/heads/main')]

parameters:
  - name: deployTest
    displayName: Force Test Deployment
    type: boolean
    default: false

  - name: webApps
    type: object
    default:
      - appName: "Web"
      - appName: "Cms"
        dependsOn: "Web"
      - appName: "Admin"
        dependsOn: "Cms"

stages:
  - stage: DeployTest
    displayName: Deploy env:Test
    condition: and( succeeded() , or( eq( ${{ parameters.deployTest }}, true), eq(variables.isMainBranch, true) ) )
    jobs:
      - ${{ each app in parameters.webApps }}:
          - template: "sub-template.yml"
            parameters:
              appName: ${{ app.appName}}
              dependsOn: ${{ app.dependsOn}}
