parameters:
- name: appName
  type: string

- name: dependsOn
  type: string
  default: ''
   
jobs:
  - job: ${{ parameters.appName}}
    displayName: Build ${{ parameters.appName }}
    dependsOn: ${{ parameters.dependsOn }}
    steps:
    - script: echo Hello, world!
      displayName: 'Run a one-line script'

    - task: PowerShell@2
      inputs:
        targetType: 'inline'
        script: 'Start-Sleep -Seconds 30'
      
   