# This is a basic workflow to help you get started with Actions

name: Pull Request Workflow
on:
  pull_request:
    types: [ready_for_review ]

permissions:
  pull-requests: write

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  run:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
    - name: PR comment
      uses: github-actions-up-and-running/pr-comment@v1.0.1
      with:
        # GITHUB_TOKEN secret
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        # Message to comment
        message: '/azp run' 
